5hseok/DODAL_BE_SERVER

- .idea/.name
- .idea/gradle.xml
- build.gradle
- src/main/java/ac/dnd/dodal/config/JasyptConfig.java
- src/main/resources/application.yml
Linked Feature backlog: close #1 
Jasypt로 Environment를 암호화
Jasypt library를 추가하고, JasyptConfig class를 생성하여 관련 설정을 추가한다.
> [FEAT] Environment 암호화

- src/main/java/ac/dnd/Main.java
- src/main/java/ac/dnd/dodal/DodalApplication.java
Main class를 `@SpringbootApplication` annotation과 함께 DodalApplication으로 명명한다.
기존에는 application name이 생성되지 않아 root folder에 dodal을 추가하고, 이에 맞게 main class도 변경하였다.
> [REFACTOR] Rename Main -> DodalApplication

- .github/workflows/ForkRepoCI.yml
- build.gradle
CI 시 발생하는 jacoco & sonar issue를 해결한다.
- test가 하나도 존재하지 않는 경우 report가 생성되지 않아 에러가 생겼다
- 구현된 기능이 적어 && coverage check가 필요 없는 클래스들은 exclude로 추가하였다
- CI workflow에서 test와 build를 나누었다
- 리뷰어를 추가했다
> [FIX] Jacoco & Sonar 

- src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
Base entity needs noargs and superbuilder annotaition.
+ Fields must be opened to child classes -> change to protected
> [REFACTOR] Base Entity

- .github/workflows/ForkRepoCI.yml
- build.gradle
- src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
- src/main/java/ac/dnd/dodal/domain/goal/constraint/GoalConstraint.java
- src/main/java/ac/dnd/dodal/domain/goal/exception/GoalExceptionCode.java
- src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
- src/main/java/ac/dnd/dodal/ui/goal/request/GoalCreateRequest.java
- src/test/java/ac/dnd/dodal/AcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/AchieveGoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/CreateGoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/DeleteGoalAcceptanceTets.java
- src/test/java/ac/dnd/dodal/acceptance/goal/GoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
- src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
- src/test/java/ac/dnd/dodal/ui/fixture/UIFixture.java
- src/test/java/ac/dnd/dodal/ui/goal/fixture/GoalUIFixture.java
- src/test/resources/application-test.yml
Linked Feature backlog: Related to [issue#3](https://github.com/dnd-side-project/dnd-12th-2-backend/issues/3)
Goal의 Command에 대한 인수 테스트를 진행한다.
인수 테스트는 RestAssured를 사용하여 실제 웹환경처럼 작동하게끔 한다.
이때, context 생성 비용을 아끼기 위해 가급적 같은 환경끼리 묶어서 돌아가게끔 한다. -> AcceptanceTest, IntegrationTest abstract class
swagger, api docs 대신 이것을 전달한다. 이를 위해 모든 예외 처리를 포함하여 더 꼼꼼하게 작성하였다.
현재 로직은 구현되지 않아 당연히 실패하는 게 맞는 테스트이다.
- 시각화 (조회. query)의 경우 요구사항이 명확히 정해지지도 않았을 뿐더러, 
- query의 중요도 및 복잡도가 올라감에 따라 CQS pattern, 후에는 CQRS에 대한 확장까지 고려중이기 떄문이다.
원래는 AcceptanceTest의 경우 test container를 사용하여 production 환경과 최대한 유사하게 구성하려고 했으나, container까지는 띄워지나 connection이 되지 않았다.
당장 여기에 더이상 신경쓸 수 없어 넘어갔다.
인수 테스트는 실제 유저 시나리오를 구현해야하기 때문에 authorization도 함께 검사된다.
단, 이 경우 token값을 어떻게 해야할지 생각을 해봐야할 것 같다.
당장에는 테스트용으로 기한이 긴 토큰 한 쌍을 만들고, 테스트끼리의 순서를 조정하여 앞에서 …
> [FEAT] Goal Command AcceptanceTest

- src/main/java/ac/dnd/dodal/application/goal/dto/command/AchieveGoalCommand.java
- src/main/java/ac/dnd/dodal/application/goal/dto/command/CreateGoalCommand.java
- src/main/java/ac/dnd/dodal/application/goal/dto/command/DeleteGoalCommand.java
- src/main/java/ac/dnd/dodal/application/goal/repository/GoalCommandRepository.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
- src/main/java/ac/dnd/dodal/application/goal/usecase/AchieveGoalUseCase.java
- src/main/java/ac/dnd/dodal/application/goal/usecase/CreateGoalUseCase.java
- src/main/java/ac/dnd/dodal/application/goal/usecase/DeleteGoalUseCase.java
- src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
- src/test/java/ac/dnd/dodal/application/goal/dto/GoalCommandFixture.java
- src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
- src/test/java/ac/dnd/dodal/domain/goal/GoalFixture.java
Linked Feature backlog: [issue#3](https://github.com/dnd-side-project/dnd-12th-2-backend/issues/3)
Implement Goal Command (Change of data)'s logic and verify it with unit test
1. dto/model
2. use case
3. service with no body
4. repository (also interface)
5. fixture
6. unit test
7. implement service
-   [x] If a new feature has been added, or a bug fixed, has a test been added to confirm good behavior?
-   [x] Does the test successfully test edge and corner cases?
> [FEAT] Goal Command Application

- src/main/java/ac/dnd/dodal/application/goal/repository/GoalRepository.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalService.java
- src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
- src/test/java/ac/dnd/dodal/application/goal/service/GoalServiceTest.java
Goal Service를 구현한다.
Command, Query는 결국 api 요청에 대해서 수행된다. 그 어디에도 포함되지 않는 기능들의 경우 기본 Service로 생성하고, 이것을 사용하도록 구현했다. 또한 주 데이터베이스는 결국 command가 수행되는 것이고, 이는 일반 service에서도 접근 가능하므로 일반 repository로 정정했다.
기본적인 기능을 분리함에 따라 commandService에서도 핵심 로직에만 집중할 수 있다.
-   [x] If a new feature has been added, or a bug fixed, has a test been added to confirm good behavior?
-   [x] Does the test successfully test edge and corner cases?
> [FEAT] Goal Service

- src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
- src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
- src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
- src/main/java/ac/dnd/dodal/ui/goal/request/CreateGoalRequest.java
- src/main/resources/db/migration/V3__sample_data.sql
- src/test/java/ac/dnd/dodal/acceptance/goal/AchieveGoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/CreateGoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
- src/test/java/ac/dnd/dodal/ui/goal/fixture/GoalUIFixture.java
Linked Feature backlog: [issue#3](https://github.com/dnd-side-project/dnd-12th-2-backend/issues/3)
Goal Command API를 구현한다.
Controller / repository test는 시간관계상 생략했다.
실제 환경과 가장 유사한 Acceptance test 주 로직-Service layer에 대한 단위테스트만 존재한다.
-   [x] If a new feature has been added, or a bug fixed, has a test been added to confirm good behavior?
-   [x] Does the test successfully test edge and corner cases?
> [FEAT] Goal Command API

- src/main/java/ac/dnd/dodal/domain/user/model/User.java
- src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
- src/main/resources/db/migration/V6__sample_data.sql
- src/test/java/ac/dnd/dodal/AcceptanceTest.java
- src/test/java/ac/dnd/dodal/IntegrationTest.java
- src/test/java/ac/dnd/dodal/acceptance/hello/HelloAcceptanceTest.java
- src/test/java/ac/dnd/dodal/application/user/HelloControllerTest.java
- src/test/java/ac/dnd/dodal/core/security/util/JwtUtilTest.java
Spring security를 적용한다.
- 기존 Controller에서 `@UserId` 사용해서 user id 받아오기
- 만료되지 않는 토큰을 갖는 user 1 설정, Acceptance test에 공통 token 적용
- 토큰 생성을 위한 JwtUtilTest 작성
-   [x] If a new feature has been added, or a bug fixed, has a test been added to confirm good behavior?
> [REFACTOR] Apply Authorization

- src/main/java/ac/dnd/dodal/common/model/BaseEntity.java
- src/main/java/ac/dnd/dodal/core/security/JwtAuthEntryPoint.java
- src/main/java/ac/dnd/dodal/core/security/config/SecurityConfig.java
- src/main/java/ac/dnd/dodal/core/security/filter/JwtAuthenticationFilter.java
- src/main/java/ac/dnd/dodal/core/security/filter/JwtExceptionFilter.java
- src/main/java/ac/dnd/dodal/core/security/handler/JwtAccessDeniedHandler.java
- src/main/java/ac/dnd/dodal/ui/hello/HelloController.java
- src/main/java/ac/dnd/dodal/ui/user/response/JwtTokenDto.java
> [REFACTOR] Remove all unused import statement

- src/main/java/ac/dnd/dodal/domain/user/model/User.java
apple login PR 머지 시 User 엔티티에 있던 apple refresh token이 사라지지 않는 현상을 수정했습니다.
배포 시에 생길 수 있는 문제를 찾다가 발견되었습니다.
> [FIX] Apple Refresh Token 삭제 

- src/main/resources/db/migration/V99__sample_data.sql
- src/test/java/ac/dnd/dodal/flyway/FlywayTest.java
MySQL와의 호환성 문제로 체크되지 않았던 flyway 문제를 해결, sample data 추가 sql문의 버전을 99로 하여서 추후 수정이 용이하게 바꿈
> [REFACTOR] Flyway

- src/main/java/ac/dnd/dodal/application/goal/repository/GoalStatisticsRepository.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalStatisticsEventListener.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalStatisticsService.java
- src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
- src/main/java/ac/dnd/dodal/application/plan/usecase/AddPlanUseCase.java
- src/main/java/ac/dnd/dodal/application/plan/usecase/CreatePlanAndHistoryUseCase.java
- src/main/java/ac/dnd/dodal/application/plan_history/repository/HistoryStatisticsRepository.java
- src/main/java/ac/dnd/dodal/application/plan_history/service/HistoryStatisticsEventListenter.java
- src/main/java/ac/dnd/dodal/application/plan_history/service/HistoryStatisticsService.java
- src/main/java/ac/dnd/dodal/domain/goal/event/GoalCreatedEvent.java
- src/main/java/ac/dnd/dodal/domain/goal/exception/GoalExceptionCode.java
- src/main/java/ac/dnd/dodal/domain/goal/model/GoalStatistics.java
- src/main/java/ac/dnd/dodal/domain/plan/event/PlanCompletedEvent.java
- src/main/java/ac/dnd/dodal/domain/plan_history/exception/PlanHistoryExceptionCode.java
- src/main/java/ac/dnd/dodal/domain/plan_history/model/HistoryStatistics.java
- src/main/java/ac/dnd/dodal/ui/goal/GoalPlanController.java
- src/main/resources/db/migration/V101__add_statistics_data.sql
- src/main/resources/db/migration/V9__add_statistic_table.sql
- src/main/resources/db/migration/V9_add_statistic_table.sql
- src/test/java/ac/dnd/dodal/application/goal/service/GoalCommandServiceTest.java
- src/test/java/ac/dnd/dodal/application/goal/service/GoalStatisticsEventListenerTest.java
> Feat 32/statistics hj

- src/main/java/ac/dnd/dodal/domain/goal/exception/GoalExceptionCode.java
- src/main/java/ac/dnd/dodal/domain/plan/exception/PlanExceptionCode.java
> refactor(ExceptionCode): Remove _ from code

- src/main/java/ac/dnd/dodal/application/user/service/AuthLoginService.java
- src/main/java/ac/dnd/dodal/ui/auth/request/OAuthByAppleUserInfoRequestDto.java
> :recycle: refactor(apple_login): 애플 로그인 로직 수정

- src/main/java/ac/dnd/dodal/application/user/repository/UserAnswerRepository.java
- src/main/java/ac/dnd/dodal/application/user/service/UserQueryService.java
- src/main/java/ac/dnd/dodal/application/user/usecase/CheckIsDoneUserAnswerUseCase.java
- src/main/java/ac/dnd/dodal/domain/onboarding/exception/OnBoardingExceptionCode.java
- src/main/java/ac/dnd/dodal/ui/user/UserController.java
- src/main/java/ac/dnd/dodal/ui/user/response/GetUserAnswerResponseDto.java
온보딩 데이터를 반환.
온보딩 데이터가 존재하면 사용자의 온보딩 데이터를 반환하고, 온보딩 데이터가 존재하지 않는다면 예외를 반환합니다.
PR 확인 되셨다면 바로 merge까지 부탁드려요!
> [FEAT] 사용자 온보딩 데이터 확인 API 구현 

- src/main/java/ac/dnd/dodal/application/goal/repository/GoalRepository.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalQueryService.java
- src/main/java/ac/dnd/dodal/application/goal/usecase/GetGoalUseCase.java
- src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
- src/main/java/ac/dnd/dodal/ui/goal/response/GoalStatisticsResponse.java
- src/test/java/ac/dnd/dodal/acceptance/goal/GetGoalsAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/steps/GetGoalsSteps.java
> [FEAT] Achieved 유무에 따른 User별 목표 리스트 조회

- src/main/java/ac/dnd/dodal/application/feedback/repository/DefaultFeedbackIndicatorRepository.java
- src/main/java/ac/dnd/dodal/application/feedback/repository/FeedbackQuestionRepository.java
- src/main/java/ac/dnd/dodal/application/feedback/service/DefaultFeedbackIndicatorService.java
- src/main/java/ac/dnd/dodal/application/feedback/service/FeedbackFacadeService.java
- src/main/java/ac/dnd/dodal/application/feedback/service/FeedbackQuestionService.java
- src/main/java/ac/dnd/dodal/application/feedback/usecase/GetFeedbackQuestionAndIndicatorUseCase.java
- src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
- src/main/java/ac/dnd/dodal/application/plan_feedback/repository/PlanFeedbackRepository.java
- src/main/java/ac/dnd/dodal/application/plan_feedback/service/PlanFeedbackService.java
- src/main/java/ac/dnd/dodal/common/constant/Constants.java
- src/main/java/ac/dnd/dodal/domain/feedback/enums/FeedbackType.java
- src/main/java/ac/dnd/dodal/domain/feedback/model/DefaultFeedbackIndicator.java
- src/main/java/ac/dnd/dodal/domain/feedback/model/DefaultFeedbackIndicatorId.java
- src/main/java/ac/dnd/dodal/domain/feedback/model/FeedbackQuestion.java
- src/main/java/ac/dnd/dodal/domain/feedback/model/FeedbackQuestionId.java
- src/main/java/ac/dnd/dodal/ui/feedback/FeedbackController.java
- src/main/java/ac/dnd/dodal/ui/feedback/response/FeedbackQuestionAndIndicatorElement.java
- src/main/java/ac/dnd/dodal/ui/feedback/response/FeedbackQuestionAndIndicatorsResponse.java
- src/main/resources/db/migration/V15__change_feedback_question.sql
- src/test/java/ac/dnd/dodal/acceptance/feedback/GetFeedbackQuestionAndIndicatorsAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/feedback/steps/GetFeedbackQuestionAndIndicatorsStep.java
- src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
Linked Feature backlog: close #76 
필요한 질문과 지표들을 type에 따라 조회하는 API를 구한다.
인수테스트까지 구현함
> [FEAT #76] 피드백 질문 / 지표 조회 API

- src/main/java/ac/dnd/dodal/application/goal/dto/command/UpdateGoalCommand.java
- src/main/java/ac/dnd/dodal/application/goal/service/GoalCommandService.java
- src/main/java/ac/dnd/dodal/application/goal/usecase/UpdateGoalUseCase.java
- src/main/java/ac/dnd/dodal/domain/goal/model/Goal.java
- src/main/java/ac/dnd/dodal/ui/goal/GoalController.java
- src/test/java/ac/dnd/dodal/acceptance/goal/UpdateGoalAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/goal/steps/GoalSteps.java
> [FEAT] 목표 title 수정 기능 구현

- src/main/java/ac/dnd/dodal/application/plan/repository/PlanRepository.java
- src/main/java/ac/dnd/dodal/application/plan/service/PlanCommandService.java
- src/main/java/ac/dnd/dodal/application/plan/service/PlanService.java
- src/main/java/ac/dnd/dodal/application/plan/usecase/CompletePlanUseCase.java
- src/main/java/ac/dnd/dodal/ui/plan/PlanController.java
- src/test/java/ac/dnd/dodal/acceptance/auth/withdrawUserAcceptanceTest.java
- src/test/java/ac/dnd/dodal/acceptance/plan/PlanAcceptanceTest.java
- src/test/java/ac/dnd/dodal/application/plan/service/PlanCommandServiceTest.java
계획을 완료했을 시 가장 오래된 계획 2개와 현재 완료한 계획 1개를 포함하여 총 3개를 반환하도록 했습니다. 
> [REFACTOR] 계획 완료 시 조회되는 목록 로직 수정

- src/main/resources/application.yml
> :adhesive_bandage: fix(user): client-id 수정

- build.gradle
> :construction: chore(build.gradle): sonarqube 연동 위한 build.gradle 수정

- src/main/java/ac/dnd/dodal/application/onboarding/repository/QuestionRepository.java
- src/main/java/ac/dnd/dodal/application/plan/repository/PlanRepository.java
- src/main/java/ac/dnd/dodal/application/plan_feedback/repository/PlanFeedbackRepository.java
- src/main/java/ac/dnd/dodal/application/plan_history/repository/PlanHistoryRepository.java
- src/main/java/ac/dnd/dodal/application/user_guide/repository/UserGuideRepository.java
- src/test/java/ac/dnd/dodal/domain/user/UserFixture.java
> [REFACTOR] Repository 내의 메서드 deletedAt IS NULL 통일 
